# Generated by Django 5.0.4 on 2024-04-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformsLessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dars_title', models.CharField(max_length=80)),
                ('youtube_logo', models.ImageField(upload_to='youtube/images/')),
                ('category', models.CharField(choices=[('upwork', 'upwork'), ('kwork', 'kwork'), ('toptal', 'toptal')], max_length=25)),
                ('author', models.CharField(max_length=75)),
                ('youtube_link', models.URLField()),
            ],
        ),
    ]
