# Generated by Django 5.0.4 on 2024-04-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='otp_number',
            field=models.IntegerField(blank=True, max_length=6, null=True),
        ),
    ]
