# Generated by Django 5.0.4 on 2024-04-26 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_otp_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='otp_number',
        ),
    ]
