# Generated by Django 5.1.8 on 2025-05-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('upwork', 'Upwork'), ('kwork', 'Kwork'), ('toptal', 'Toptal')], max_length=20)),
                ('is_recommend', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformsLessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dars_title', models.CharField(max_length=80)),
                ('youtube_logo', models.ImageField(upload_to='youtube/images/')),
                ('category', models.CharField(choices=[('upwork', 'upwork'), ('kwork', 'kwork'), ('toptal', 'toptal')], max_length=25)),
                ('author', models.CharField(max_length=75)),
                ('youtube_link', models.URLField()),
            ],
        ),
    ]
