# Generated by Django 5.0.4 on 2024-04-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telegram', models.URLField(default='https://t.me/username')),
                ('instagram', models.URLField(default='https://instagram.com/username')),
                ('facebook', models.URLField(default='https://facebook.com/username')),
                ('me', models.CharField(blank=True, choices=[('oldin ishlamaganman', 'Oldin ishlamaganman'), ('junior', 'Junior dasturchiman'), ('middle', 'Middle dasturchiman'), ('senior', 'Senior dasturchiman')], max_length=50, null=True)),
                ('working_location', models.CharField(blank=True, choices=[('fergana', 'Fergana'), ('andijan', 'Andijan'), ('namangan', 'Namangan'), ('tashkent', 'Tashkent'), ('other', 'Other')], max_length=24, null=True)),
                ('company', models.CharField(blank=True, max_length=150, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('finished_test', models.DateTimeField(blank=True, null=True)),
                ('total_results', models.SmallIntegerField(blank=True, null=True)),
                ('is_failed', models.BooleanField(default=False)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='users/profile/images/')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superadmin', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_question', models.CharField(max_length=200)),
                ('a', models.CharField(blank=True, max_length=200, null=True)),
                ('b', models.CharField(blank=True, max_length=200, null=True)),
                ('c', models.CharField(blank=True, max_length=200, null=True)),
                ('d', models.CharField(blank=True, max_length=200, null=True)),
                ('correct_answer', models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=14, null=True)),
            ],
        ),
    ]
