# Generated by Django 5.0.4 on 2024-04-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='working_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
