# Generated by Django 5.0.4 on 2024-04-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_working_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
