# Generated by Django 5.0.4 on 2024-04-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('little_title', models.CharField(max_length=200)),
                ('big_title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('link_site', models.URLField(blank=True, null=True)),
                ('link_name', models.CharField(max_length=80)),
                ('video', models.FileField(blank=True, null=True, upload_to='welcome/videos/')),
                ('whats_video', models.CharField(max_length=150)),
            ],
        ),
    ]
