# Generated by Django 5.1.8 on 2025-05-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('class_name', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platforms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('about', models.TextField()),
                ('image', models.ImageField(upload_to='platforms/images/')),
                ('blog_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('little_title', models.CharField(max_length=200)),
                ('big_title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('link_site', models.URLField(blank=True, null=True)),
                ('link_name', models.CharField(max_length=80)),
                ('video', models.FileField(blank=True, null=True, upload_to='welcome/videos/')),
                ('whats_video', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SiteUsersAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students', models.SmallIntegerField()),
                ('total_courses', models.SmallIntegerField()),
                ('finished_courses', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=80)),
                ('full_name', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profiles/images/team/')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
