# Generated by Django 5.0.4 on 2024-04-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rateus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/rating/'),
        ),
        migrations.AddField(
            model_name='rateus',
            name='working',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
